---
 - name: Configure admin sudo setup
   hosts: all
   become: yes
   tasks:
     - name: Take backup of sudoers.d 
       shell: "cp -rp /etc/sudoers.d /etc/sudoers.d.{{ ansible_date_time.date }}.{{ ansible_date_time.time }}.bkup"
    
     - name: Take backup of sudoers
       shell: "cp -p /etc/sudoers /etc/sudoers.{{ ansible_date_time.date }}.{{ ansible_date_time.time }}.bkup"

     - name: Copy sudoers template from src to dest
       copy:
         src: 010_STD_SA_GLB
         dest: /etc/sudoers.d
         mode: '0440'

     - name: Insert the template line in sudoers
       lineinfile: 
         path: /etc/sudoers
         line: '#include /etc/sudoers.d/010_STD_SA_GLB'
         insertafter: '#include /etc/sudoers.d/010_STD_NEG_GLB'
         validate: /usr/sbin/visudo -cf %s

