---
 - name: "Copy TSM package to Power Linux server"
   copy: 
    src: /home/ansible/Rekha-Playbooks/TSM-Blueiron/tasks/LINUX/TSMPACKAGE/PPC64
    dest: "/tmp/"
    mode: "0777"
   when: ansible_architecture == 'ppc64le'

 - name: "Copy TSM pcakage to X86"
   copy:
    src: /home/ansible/Rekha-Playbooks/TSM-Blueiron/tasks/LINUX/TSMPACKAGE/X86
    dest: "/tmp/"
    mode: '0777'
   when: ansible_architecture == 'x86_64'

 - name:  "Install TSM Package"
   command:
    cmd: rpm -ivh "{{ item }}"
    warn: false
   loop: 
     - /tmp/PPC64/gskcrypt*
     - /tmp/PPC64/gskssl*
     - /tmp/PPC64/TIVsm-API64*
     - /tmp/PPC64/TIVsm-BA*
   when: ansible_architecture == 'ppc64le'

 - name:  "Install TSM Package"
   command:
    cmd: rpm -ivh "{{ item }}"
    warn: false
   loop:
     - /tmp/X86/gskcrypt*
     - /tmp/X86/gskssl*
     - /tmp/X86/TIVsm-API64*
     - /tmp/X86/TIVsm-BA*
   when: ansible_architecture == 'x86_64'

 - name: "Edit dsm.opt"
   template:
     src: /home/ansible/Rekha-Playbooks/TSM-Blueiron/templates/dsm.opt.j2
     dest: /opt/tivoli/tsm/client/ba/bin/dsm.opt
     mode: '0755'

 - name: "Edit dsm.sys"
   template:
     src: /home/ansible/Rekha-Playbooks/TSM-Blueiron/templates/dsm.sys-linux.j2
     dest: /opt/tivoli/tsm/client/ba/bin/dsm.sys
     mode: '0755'

 - name: "Create initsched"
   template:
     src: /home/ansible/Rekha-Playbooks/TSM-Blueiron/templates/init_sched-linux.j2
     dest: /opt/tivoli/tsm/client/ba/bin/init_sched.sh
     mode: '0755'

 - name: "Create dsm file in etc"
   template:
     src: /home/ansible/Rekha-Playbooks/TSM-Blueiron/templates/dsm.service-linux.j2
     dest: /etc/systemd/system/dsm.service

 - name: Enable the dsmc file
   service:
     name: dsm
     state: started
     enabled: yes

