---
 - name: "Install and configure TSM on AIX"
   hosts: AIX
   become: yes
   tasks:
     - name: "Include AIX tasks"
       include_tasks: aix.yml

 - name: "Install and configure TSM on Linux"
   hosts: LINUX
   become: yes
   tasks:
     - name: "Include Linux Tasks"
       include_tasks: linux.yml

     
