---
 - hosts: LPAR2RRD
   become: yes 
   vars_prompt: 
    - name: crontabpath
      prompt: "Enter the LPAR2RRD WEB PATH"
      private: no
   tasks:
    - name: "Copy the package from local to repo if linux"
      copy: src=/home/ansible/Rekha-Playbooks/LPAR2RRD/lpar2rrd-agent-7.00-1.noarch.rpm dest=/tmp/LPAR2RRD/
      when: ansible_distribution == "RedHat"

    - name: "Copy the package from local to client server id AIX"
      copy: src=/home/ansible/Rekha-Playbooks/LPAR2RRD/lpar2rrd-agent-7.00-1.ppc.rpm dest=/tmp/LPAR2RRD/
      when: ansible_distribution == "AIX"

    - name: "Install the package"
      command:
       cmd: rpm -ivh /tmp/LPAR2RRD/*.rpm
       warn: false
 
    - name: "Add the entry in crontab"
      cron: 
       name: "LPAR2RRD entry to cron"
       job: /usr/bin/perl /opt/lpar2rrd-agent/lpar2rrd-agent.pl {{ crontabpath }} > /var/tmp/lpar2rrd-agent.out 2>&1
