---
 - hosts: TSM
   become: yes
   serial: 1
   vars_prompt: 
    - name: servername
      prompt: "Servername as per Blueiron Portal"
      private: no
    - name: TCPIP
      prompt: "enter TCP IP address as per Blueiron Portal"
      private: no
    - name: CID
      prompt: "Enter node name as per Blueiron Portal"
      private: no
   tasks: 
    - name: "Copy TSM backupage from local to remote"
      copy:
       src: "/home/ansible/TSMPlaybooks/TSMPackages"
       dest: "/tmp"
       mode: '0777' 
   
    - name: "Install TSM Package"
      command:
       cmd: rpm -ivh "{{ item }}"
       warn: false
      loop: 
       - /tmp/TSMPackages/gskcrypt*
       - /tmp/TSMPackages/gskssl*
       - /tmp/TSMPackages/TIVsm-API64.x86_64.rpm
       - /tmp/TSMPackages/TIVsm-BA.x86_64.rpm
 
    - name: "Edit dsm.opt"
      template:
        src: /home/ansible/TSMPlaybooks/dsm.opt
        dest: /opt/tivoli/tsm/client/ba/bin/dsm.opt
        mode: '755'

    - name: "Edit the dsm.sys file"
      template:
        src: /home/ansible/TSMPlaybooks/dsm.sys 
        dest: /opt/tivoli/tsm/client/ba/bin/dsm.sys
        mode: '755'
    
    - name: "Create initsched"
      template:
        src: /home/ansible/TSMPlaybooks/init_sched.sh
        dest: /opt/tivoli/tsm/client/ba/bin/init_sched.sh
        mode: '755'

    - name: "Create dsm file in etc"
      template:
        src: /home/ansible/TSMPlaybooks/dsm.service
        dest: /etc/systemd/system/dsm.service
  
    - name: Create symlink 
      command: 
       cmd: systemctl enable dsm.service
