---
 - name: "Copy Java package and install on AIX servers"
   hosts: JAVA
   become: true
   vars:
    remote_dir: /tmp/
   tasks:
    - name: "Copy Java package from Local to Remote"
      copy: 
       src: "/home/ansible/Rekha-Playbooks/JAVA/JAVAPACKAGE"
       dest: "{{ remote_dir }}"
       mode: '0777'

    - name: "Install the Java Package"
      shell:
       cmd: cd /tmp/JAVAPACKAGE && installp -agXYd . Java8_64.jre Java8_64.sdk Java8_64.jclsource Java7_64.jre  Java7_64.sdk Java7_64.jclsource Java8.jre  Java8.sdk Java8.jclsource 2>&1 | tee installp.log

    - name: "Get Java version output"
      shell: 
       cmd: lslpp -la | grep -i Java
      register: Javaversion_output
      
    - name: "Print Output of Java version"
      debug:
       var: Javaversion_output.stdout_lines
