---
 - name: "Copy TSM backupage from local to remote"
   copy: 
    src: /home/ansible/Rekha-Playbooks/TSM-Blueiron/tasks/AIX/TSMPACKAGE
    dest: /tmp
    mode: '0777'

 - name: "Install tsm packages"
   installp:
     name: all 
     repository_path: /tmp/TSMPACKAGE
     accept_license: yes
     state: present

 - name: "Edit dsm.opt"
   template:
     src: /home/ansible/Rekha-Playbooks/TSM-Blueiron/templates/dsm.opt.j2
     dest: /usr/tivoli/tsm/client/ba/bin64/dsm.opt
     mode: '0755'

 - name: "Edit the dsm.sys file"
   template:
     src: /home/ansible/Rekha-Playbooks/TSM-Blueiron/templates/dsm.sys-aix.j2
     dest: /usr/tivoli/tsm/client/ba/bin64/dsm.sys
     mode: '0755'

 - name: "Create initsched"
   template:
     src: /home/ansible/Rekha-Playbooks/TSM-Blueiron/templates/init_sched-aix.j2
     dest: /usr/tivoli/tsm/client/ba/bin64/init_sched.sh
     mode: '0755'

 - name:  "Take inittab backup"
   shell: "cp -p /etc/inittab  /etc/inittab.bak.beforetsm.{{ ansible_date_time.date }}.{{ ansible_date_time.time }}"

 - name: "add tsm entry in inittab"
   aix_inittab:
     name: tsm
     runlevel: 2
     action: once
     command: /usr/tivoli/tsm/client/ba/bin64/dsmcad -optfile=/usr/tivoli/tsm/client/ba/bin64/dsm.opt >/dev/null # OS backup
     state: present

 - name: "start dsm service"
   command: sh /usr/tivoli/tsm/client/ba/bin64/init_sched.sh


