---
 - name: "Copy Java package and install on AIX servers"
   hosts: JAVA
   become: true
   tasks:
    - name: "Get Java version output"
      shell: 
       cmd: lslpp -la | grep -i Java
      register: Javaversion_output
      
    - name: "Print Output of Java version"
      debug:
       var: Javaversion_output.stdout_lines
